### ISSUE TITLE
Unexpected Github Actions Output

### ISSUE THREAD

**Issue by Numie** [nshki/chusaku#31]
Absolutely loving this gem! In order to use in production, we want to implement a Github Actions check to validate that route annotations are up to date. When attempting to implement the workflow, I ran `chusaku` in the root directory but reverted the changes in one file to test the workflow.

Expected output:
```
Chusaku has finished running.
This was a dry run so no files were changed.
Exited with status code 1.
```

Output when running locally:
```
$ bundle exec chusaku --dry-run --exit-with-error-on-annotation
Chusaku has finished running.
This was a dry run so no files were changed.
Exited with status code 1.
```

Output in Github Actions Workflow:
```
Run bundle exec chusaku --dry-run --exit-with-error-on-annotation
  bundle exec chusaku --dry-run --exit-with-error-on-annotation
  shell: /usr/bin/bash -e {0}
Nothing to annotate.
```

Github Action Workflow:
```
name: Chusaku Check

on: pull_request

jobs:
  chusaku:
    name: Chusaku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Chusaku
        run: bundle exec chusaku --dry-run --exit-with-error-on-annotation
```

Running Ruby 2.7.6 and Rails 6.0.4.8. Got the same output in the Github Actions workflow when omitting the `--dry-run` flag for what it's worth.

**Comment by nshki** [comment]
Hi there! I'm so glad that you're finding the gem useful, and thanks so much for opening this issue.

I went ahead and spun up a brand new Rails v6.0.4.8 project with Ruby 2.7.6 and tried the GA workflow that you have with one new controller action. It _did_ error out, but not in the way you described, as can be seen in this screenshot:

![Screenshot 2022-06-24 at 08-21-36 Issue 31 · nshki_chusaku-test@f5bec1f](https://user-images.githubusercontent.com/1121087/175567718-aa80b55e-e37c-43c2-a7b3-0b1fd5dfdcad.png)

This particular error was from not having Yarn packages installed, so I used the following workflow config and gave it a re-run:

```yaml
name: Chusaku

on: pull_request

jobs:
  chusaku:
    name: Chusaku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v3
      - name: Run Yarn
        run: yarn install
      - name: Run Chusaku
        run: bundle exec chusaku --dry-run --exit-with-error-on-annotation
```

![Screenshot 2022-06-24 at 08-25-36 Issue 31 · nshki_chusaku-test@f75fa03](https://user-images.githubusercontent.com/1121087/175568107-e8d1ab64-d388-43e6-a8cc-0519fc5dd110.png)

This time, it did work as expected.

Your local output and workflow output definitely suggest that you checked in the expected file changes, but just to make sure, it may be worth double-checking the state of your controller(s) and routes on the PR that you're seeing this issue on.
